### ISSUE TITLE
iOS 15 SDK support

### ISSUE THREAD

**Issue by andrey-krukovskiy** [qonversion/qonversion-ios-sdk#200] opened 2021-07-30 19:07 UTC
Can't build for iOS 15
got error `'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.`

**Comment by suriksarkisyan** [comment] 2021-08-08 20:15
Hi, @andrey-krukovskiy, sorry for the late reply.
We will fix that issue ASAP, keep in touch! I'll update this issue when a fix will be released.

**Comment by kellvembarbosa** [comment] 2021-08-13 00:25
Awaiting update...

**Comment by suriksarkisyan** [comment] 2021-08-15 21:41
Hi guys, sorry for the late reply!
A possible fix is ready. I'll test the fix on all dependencies managers that we support and will do my best to release it tomorrow. Let's keep in touch!

**Comment by suriksarkisyan** [comment] 2021-08-16 11:50
@andrey-krukovskiy @kellvembarbosa 
Could you please provide information about what dependency manager do you use? Cocoapods/SPM/Carthage?

For SPM this issue is fixed in Xcode 13 beta 5. Here are [release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-13-beta-release-notes):
`You don’t need to annotate code as unavailable for use in application extensions if it references APIs annotated as unavailable for use in application extensions. This reverts a requirement that Xcode 13 Beta 3 introduced. (80615922) (FB9332020)`

For Cocoapods the problem is still occurring in case you add Qonversion SDK to your extension. Are you use SPM or just using Qonversion SDK in the extension?

Anyway, I'll release the fix soon. Just want to know and cover all cases.

**Comment by andrey-krukovskiy** [comment] 2021-08-16 12:52
@suriksarkisyan I've used SPM

**Comment by suriksarkisyan** [comment] 2021-08-16 12:59
@andrey-krukovskiy Cool! It means there are no blocks for you to test iOS 15 right now. All you need is just update Xcode to beta 5.

**Comment by suriksarkisyan** [comment] 2021-08-16 15:16
Happy to say [Qonversion SDK 2.17.2](https://github.com/qonversion/qonversion-ios-sdk/releases/tag/2.17.2) published. The problem is resolved.

**Closed** 2021-08-21 20:53 UTC
